################################################################################
# BCFG I/O Ports
################################################################################

# port PULLUP
set_property PULLUP true [get_ports {IO1[0]}]
set_property PULLUP true [get_ports {IO1[1]}] ;   # MISO prom
set_property PULLUP true [get_ports {IO1[2]}] ;   # MOSI prom
set_property PULLUP true [get_ports {IO1[3]}] ;   # SCLK prom
set_property PULLUP true [get_ports {IO1[4]}] ;   # /CS prom
set_property PULLUP true [get_ports {IO1[5]}]
set_property PULLUP true [get_ports {IO1[6]}]
set_property PULLUP true [get_ports {IO1[7]}]
set_property PULLUP true [get_ports {IO1[8]}]
set_property PULLUP true [get_ports {IO1[9]}]
set_property PULLUP true [get_ports {IO1[10]}]
set_property PULLUP true [get_ports {IO1[11]}]
set_property PULLUP true [get_ports {IO1[12]}]
set_property PULLUP true [get_ports {IO1[13]}]
set_property PULLUP true [get_ports {IO1[14]}]
set_property PULLUP true [get_ports {IO1[15]}]
set_property PULLUP true [get_ports {IO1[16]}]
set_property PULLUP true [get_ports {IO1[17]}]
set_property PULLUP true [get_ports {IO1[18]}]
set_property PULLUP true [get_ports {IO1[19]}]
set_property PULLUP true [get_ports {IO1[20]}]
set_property PULLUP true [get_ports {IO1[21]}]
set_property PULLUP true [get_ports {IO1[22]}]
set_property PULLUP true [get_ports {IO1[23]}]
set_property PULLUP true [get_ports {IO1[24]}]
set_property PULLUP true [get_ports {IO1[25]}]
set_property PULLUP true [get_ports {IO1[26]}]
set_property PULLUP true [get_ports {IO1[27]}]
set_property PULLUP true [get_ports {IO1[28]}]
set_property PULLUP true [get_ports {IO1[29]}]
set_property PULLUP true [get_ports {IO1[30]}]
set_property PULLUP true [get_ports {IO1[31]}]
set_property PULLUP true [get_ports {IO1[32]}]
set_property PULLUP true [get_ports {IO1[33]}]

set_property PULLUP true [get_ports {IO2[0]}]
set_property PULLUP true [get_ports {IO2[1]}]
set_property PULLUP true [get_ports {IO2[2]}]
set_property PULLUP true [get_ports {IO2[3]}]
set_property PULLUP true [get_ports {IO2[4]}]
set_property PULLUP true [get_ports {IO2[5]}]
set_property PULLUP true [get_ports {IO2[6]}]
set_property PULLUP true [get_ports {IO2[7]}]
set_property PULLUP true [get_ports {IO2[8]}]
set_property PULLUP true [get_ports {IO2[9]}]
set_property PULLUP true [get_ports {IO2[10]}]
set_property PULLUP true [get_ports {IO2[11]}]
set_property PULLUP true [get_ports {IO2[12]}]
set_property PULLUP true [get_ports {IO2[13]}]
set_property PULLUP true [get_ports {IO2[14]}]
set_property PULLUP true [get_ports {IO2[15]}]
set_property PULLUP true [get_ports {IO2[16]}]
set_property PULLUP true [get_ports {IO2[17]}]
set_property PULLUP true [get_ports {IO2[18]}]
set_property PULLUP true [get_ports {IO2[19]}]
set_property PULLUP true [get_ports {IO2[20]}]
set_property PULLUP true [get_ports {IO2[21]}]
set_property PULLUP true [get_ports {IO2[22]}]
set_property PULLUP true [get_ports {IO2[23]}]
set_property PULLUP true [get_ports {IO2[24]}]
set_property PULLUP true [get_ports {IO2[25]}]
set_property PULLUP true [get_ports {IO2[26]}]
set_property PULLUP true [get_ports {IO2[27]}]
set_property PULLUP true [get_ports {IO2[28]}]
set_property PULLUP true [get_ports {IO2[29]}]
set_property PULLUP true [get_ports {IO2[30]}]
set_property PULLUP true [get_ports {IO2[31]}]
set_property PULLUP true [get_ports {IO2[32]}]
set_property PULLUP true [get_ports {IO2[33]}]
set_property PULLUP true [get_ports {IO2[34]}]
set_property PULLUP true [get_ports {IO2[35]}]
set_property PULLUP true [get_ports {IO2[36]}]
set_property PULLUP true [get_ports {IO2[37]}]
set_property PULLUP true [get_ports {IO2[38]}]
set_property PULLUP true [get_ports {IO2[39]}]
