################################################################################
# DRAC I/O Ports
################################################################################

# port PULLUP
set_property PULLUP true [get_ports {IO1[1]}]  ;  # MISO prom
set_property PULLUP true [get_ports {IO1[2]}]  ;  # MOSI prom
set_property PULLUP true [get_ports {IO1[3]}]  ;  # SCLK prom
set_property PULLUP true [get_ports {IO1[4]}]  ;  # /CS prom
set_property PULLUP true [get_ports {IO1[14]}] ;  # FAULTn[4]
set_property PULLUP true [get_ports {IO1[15]}] ;  # OTWn[4]
set_property PULLUP true [get_ports {IO1[26]}] ;  # RELAY_GOODn
set_property PULLUP true [get_ports {IO1[27]}] ;  # FAULTn[5]
set_property PULLUP true [get_ports {IO1[29]}] ;  # OTWn[5]
set_property PULLUP true [get_ports {IO1[30]}] ;  # ESPMV_GOODn

set_property PULLUP true [get_ports {IO2[4]}]  ;  # OTWn[3]
set_property PULLUP true [get_ports {IO2[5]}]  ;  # FAULTn[3]
set_property PULLUP true [get_ports {IO2[6]}]  ;  # LVDS_RCLK
set_property PULLUP true [get_ports {IO2[7]}]  ;  # LVDS_RDAT
set_property PULLUP true [get_ports {IO2[23]}] ;  # OTWn[2]
set_property PULLUP true [get_ports {IO2[25]}] ;  # FAULTn[2]
set_property PULLUP true [get_ports {IO2[33]}] ;  # FAULTn[1]
set_property PULLUP true [get_ports {IO2[35]}] ;  # OTWn[1]

#---------------------------------------------------------------------
# Create generated clocks
#---------------------------------------------------------------------
# adc_sck is generated by pwm clock (pwm_clk_gen_zynq), which is derived from clk1394
create_generated_clock -name adc_sck -source [get_pins {pwm_clk_gen_instance/inst/mmcm_adv_inst/CLKOUT0}] \
                       -divide_by [expr {2**2}] \
                       [get_pins {drac/PwmAdcTiming_instance/adc_clkdiv_instance/clkout_reg/Q}]

create_generated_clock -name lvds_tx_clk -source [get_ports {clk1394}] -divide_by 2 [get_pins {drac/sysclk_div2_reg/Q}]

#---------------------------------------------------------------------
# Clock groups (each group is asynchronous with respect to the others)
#   - see also clock groups in FPGA xdc file (XC7Z020.xdc)
#---------------------------------------------------------------------
set_clock_groups -async -group [get_clocks -include_generated_clocks CLK_IN1394x]
