# UseVivado
#
# This package assumes that find_package(Vivado) has been called,
# so that the XILINX_VIVADO program has been found.
#
# The basic approach is to use Vivado to create the block design, which is then
# exported (File..Export Block Design) as a TCL file, specified by the EXPORTED_TCL
# parameter. In that case, it is only necessary to put the TCL file under source
# code control, since the Vivado project is regenerated by running the TCL file.
#
# The vivado_block_build function creates a top-level TCL file, called
# make-${PROJ_NAME}.tcl, that calls ${EXPORTED_TCL}, creates the top-level Verilog
# wrapper, and generates the output files, including the final ${HW_FILE} used by Vitis.
#
# The easiest way to make changes to the block design is to open the project file
# ${PROJ_NAME}.xpr in the build directory, make the changes, and then export the
# TCL file again. This file can then be manually copied to the source directory
# to update ${EXPORTED_TCL} in the repository.
#

# Function: vivado_block_config
#
# This function updates the version number in the TCL file exported from Vivado,
# so that it can be used by different versions of Vivado.
#
# Parameters:
#   - TARGET_NAME:       Name of CMake target
#   - EXPORTED_TCL_IN:   Input file
#

function (vivado_block_config TARGET_NAME EXPORTED_TCL_IN)

  if (TARGET_NAME AND EXPORTED_TCL_IN)

    # Put the version check here, since the code below (FILE_UPDATE) is what needs
    # to be tested and possibly updated for different versions of Vivado.
    if (NOT (${Vivado_VERSION} STREQUAL "2022.2" OR
             ${Vivado_VERSION} STREQUAL "2023.1" OR
             ${Vivado_VERSION} STREQUAL "2023.2" OR
             ${Vivado_VERSION} STREQUAL "2024.1" OR
             ${Vivado_VERSION} STREQUAL "2024.2" ))
      message (WARNING "Vivado ${Vivado_VERSION} not yet tested")
    endif ()

    get_filename_component (EXPORTED_TCL_NAME ${EXPORTED_TCL_IN} NAME)
    set (EXPORTED_TCL_OUT "${CMAKE_CURRENT_BINARY_DIR}/${EXPORTED_TCL_NAME}")

    # For now, just replace version string in file, since the only substantive difference
    # between the TCL files exported by Vivado 2022.2, 2023.x, 2024.x are the version string
    # (other differences include reordering of some file content).
    # The current REGEX will match any version between "2020" and "2025", with a ".1" or ".2" suffix,
    # but this can be changed as needed. If file differences become more substantive, alternate solutions
    # include using CMake configure_file or having version-specific TCL files in the source tree.
    set (FILE_UPDATE "${CMAKE_CURRENT_BINARY_DIR}/make-update.cmake")
    file (WRITE  ${FILE_UPDATE} "# Automatically generated\n")
    file (APPEND ${FILE_UPDATE} "file (READ ${EXPORTED_TCL_IN} FILE_CONTENTS)\n")
    file (APPEND ${FILE_UPDATE}
                 "string (REGEX REPLACE \"version 202[0-5].[1-2]\" \"version ${Vivado_VERSION}\" FILE_CONTENTS \"\${FILE_CONTENTS}\")\n")
    file (APPEND ${FILE_UPDATE} "file (WRITE ${EXPORTED_TCL_OUT} \"\${FILE_CONTENTS}\")\n")

    add_custom_command (OUTPUT ${EXPORTED_TCL_OUT}
                        COMMAND ${CMAKE_COMMAND} -P ${FILE_UPDATE}
                        COMMENT "Updating ${EXPORTED_TCL_NAME}"
                        DEPENDS ${EXPORTED_TCL_IN})

    add_custom_target (${TARGET_NAME} ALL
                        COMMENT "Checking ${EXPORTED_TCL_NAME}"
                        DEPENDS ${EXPORTED_TCL_OUT})

    set_property (TARGET ${TARGET_NAME}
                         PROPERTY OUTPUT_NAME ${EXPORTED_TCL_OUT})

  else ()

    message (SEND_ERROR "vivado_block_config: required parameter missing")

  endif ()

endfunction(vivado_block_config)

# Function: vivado_block_build
#
# Parameters:
#   - PROJ_NAME:         project name
#   - BD_NAME:           board name
#   - FPGA_PARTNUM:      FPGA part number
#   - BLOCK_IN           Block design input (target that updates TCL file)
#   - HW_FILE            Output hardware file, not including path (XSA)
#

function (vivado_block_build ...)

  # set all keywords and their values to ""
  set (FUNCTION_KEYWORDS
       PROJ_NAME
       BD_NAME
       FPGA_PARTNUM
       BLOCK_IN
       HW_FILE)

  # reset local variables
  foreach(keyword ${FUNCTION_KEYWORDS})
    set (${keyword} "")
  endforeach(keyword)

  # parse input
  foreach (arg ${ARGV})
    list (FIND FUNCTION_KEYWORDS ${arg} ARGUMENT_IS_A_KEYWORD)
    if (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (CURRENT_PARAMETER ${arg})
      set (${CURRENT_PARAMETER} "")
    else (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (${CURRENT_PARAMETER} ${${CURRENT_PARAMETER}} ${arg})
    endif (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
  endforeach (arg)

  if (PROJ_NAME AND BD_NAME AND FPGA_PARTNUM AND BLOCK_IN AND HW_FILE)

    file (TO_NATIVE_PATH ${XILINX_VIVADO} VIVADO_NATIVE)

    get_property (EXPORTED_TCL TARGET ${BLOCK_IN} PROPERTY OUTPUT_NAME)

    set (HW_FILE_FULL "${CMAKE_CURRENT_BINARY_DIR}/${HW_FILE}")

    # Create TCL file
    set (TCL_FILE "${CMAKE_CURRENT_BINARY_DIR}/make-${PROJ_NAME}.tcl")
    file (WRITE  ${TCL_FILE} "create_project -force -part ${FPGA_PARTNUM} ${PROJ_NAME} ${CMAKE_CURRENT_BINARY_DIR}\n")
    file (APPEND ${TCL_FILE} "create_bd_design ${BD_NAME}\n")
    file (APPEND ${TCL_FILE} "source -notrace ${EXPORTED_TCL}\n")
    file (APPEND ${TCL_FILE} "make_wrapper -top -files [get_files ${BD_NAME}.bd]\n")
    file (APPEND ${TCL_FILE} "add_files ${CMAKE_CURRENT_BINARY_DIR}/${PROJ_NAME}.gen/sources_1/bd/${BD_NAME}/hdl/${BD_NAME}_wrapper.v\n")
    file (APPEND ${TCL_FILE} "generate_target all [get_files ${BD_NAME}.bd]\n")
    # Could add -minimal below
    file (APPEND ${TCL_FILE} "write_hw_platform -fixed -force -file ${HW_FILE_FULL}\n")
    file (APPEND ${TCL_FILE} "close_project\n")

    add_custom_command (OUTPUT ${HW_FILE_FULL}
                        COMMAND ${VIVADO_NATIVE} -nojournal -mode batch -log ${PROJ_NAME}.log -source ${TCL_FILE} -notrace
                        DEPENDS ${EXPORTED_TCL})

    add_custom_target (${PROJ_NAME} ALL
                       DEPENDS ${HW_FILE_FULL} ${BLOCK_IN})

    set_property (TARGET ${PROJ_NAME}
                         PROPERTY OUTPUT_NAME ${HW_FILE_FULL})
  else ()

    message (SEND_ERROR "vivado_block_build: required parameter missing")

  endif ()

endfunction (vivado_block_build)

# Function: vivado_block_ip
# Parameters:
#   - TARGET_NAME:       Target name
#   - IP_NAME:           IP name (in catalog)
#   - FPGA_PARTNUM:      FPGA part number
#   - BLOCK_IN           Block design input (target that updates TCL file)
#   - IPCORE_DIR         Directory for output xci file (optional)
#
# This functions sets two properties on the TARGET:
#   SOURCES      ${TARGET_NAME}.xci
#   OUTPUT_NAME  ${TARGET_NAME}_stub.v

function (vivado_block_ip)

  # set all keywords and their values to ""
  set (FUNCTION_KEYWORDS
       TARGET_NAME
       IP_NAME
       FPGA_PARTNUM
       BLOCK_IN
       IPCORE_DIR)

  # reset local variables
  foreach(keyword ${FUNCTION_KEYWORDS})
    set (${keyword} "")
  endforeach(keyword)
  # Default IPCORE_DIR is current binary directory
  set (IPCORE_DIR ${CMAKE_CURRENT_BINARY_DIR})

  # parse input
  foreach (arg ${ARGV})
    list (FIND FUNCTION_KEYWORDS ${arg} ARGUMENT_IS_A_KEYWORD)
    if (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (CURRENT_PARAMETER ${arg})
      set (${CURRENT_PARAMETER} "")
    else (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (${CURRENT_PARAMETER} ${${CURRENT_PARAMETER}} ${arg})
    endif (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
  endforeach (arg)

  if (TARGET_NAME AND IP_NAME AND FPGA_PARTNUM AND BLOCK_IN)

    file (TO_NATIVE_PATH ${XILINX_VIVADO} VIVADO_NATIVE)

    get_property (EXPORTED_TCL TARGET ${BLOCK_IN} PROPERTY OUTPUT_NAME)

    set (OUTPUT_DIR  "${IPCORE_DIR}/${TARGET_NAME}")
    set (OUTPUT_FILE_XCI     "${OUTPUT_DIR}/${TARGET_NAME}.xci")
    set (OUTPUT_FILE_VERILOG "${OUTPUT_DIR}/${TARGET_NAME}_stub.v")

    # CMake file to fix directories (gen_directory and OUTPUTDIR) in xci file
    set (FILE_UPDATE_XCI "${CMAKE_CURRENT_BINARY_DIR}/update-xci.cmake")
    file (WRITE  ${FILE_UPDATE_XCI} "# Automatically generated\n")
    file (APPEND ${FILE_UPDATE_XCI} "file (READ ${OUTPUT_FILE_XCI} FILE_CONTENTS)\n")
    file (APPEND ${FILE_UPDATE_XCI}
                 "string (REPLACE \"../.gen/sources_1/ip/${TARGET_NAME}\" \".\" FILE_CONTENTS \"\${FILE_CONTENTS}\")\n")
    file (APPEND ${FILE_UPDATE_XCI} "file (WRITE ${OUTPUT_FILE_XCI} \"\${FILE_CONTENTS}\")\n")

    # Create TCL file
    set (TCL_FILE "${CMAKE_CURRENT_BINARY_DIR}/make-${TARGET_NAME}.tcl")
    file (WRITE  ${TCL_FILE} "create_project -part ${FPGA_PARTNUM} -in_memory\n")
    file (APPEND ${TCL_FILE} "create_bd_design bd_temp\n")
    file (APPEND ${TCL_FILE} "source ${EXPORTED_TCL}\n")
    # Copy IP to IPCORE_DIR (after deleting any existing file)
    file (APPEND ${TCL_FILE} "file delete -force ${OUTPUT_DIR}\n")
    file (APPEND ${TCL_FILE} "copy_ip -name ${TARGET_NAME} -dir ${IPCORE_DIR} [get_ips *${IP_NAME}*]\n")
    file (APPEND ${TCL_FILE} "exec {${CMAKE_COMMAND}} -P ${FILE_UPDATE_XCI}\n")
    file (APPEND ${TCL_FILE} "close_project\n")
    file (APPEND ${TCL_FILE} "create_project -part ${FPGA_PARTNUM} -in_memory\n")
    # Following does not seem to work (does not change where IP output is generated), so the update-xci.cmake
    # approach was used instead (see above).
    # file (APPEND ${TCL_FILE} "set_property CUSTOMIZED_DEFAULT_IP_LOCATION ${OUTPUT_DIR} [current_project]\n")
    # Disable message 12-13650 (IP moved from original location) because it is not important
    file (APPEND ${TCL_FILE} "set_msg_config -id {Vivado 12-13650} -suppress\n")
    file (APPEND ${TCL_FILE} "read_ip ${OUTPUT_FILE_XCI}\n")
    # Generate targets and synthesize IP core
    file (APPEND ${TCL_FILE} "puts \"Synthesizing ${TARGET_NAME}\"\n")
    file (APPEND ${TCL_FILE} "set_property GENERATE_SYNTH_CHECKPOINT true [get_files ${TARGET_NAME}.xci]\n")
    file (APPEND ${TCL_FILE} "generate_target -force {instantiation_template synthesis} [get_ips ${TARGET_NAME}]\n")
    file (APPEND ${TCL_FILE} "synth_ip -force [get_ips ${TARGET_NAME}]\n")
    file (APPEND ${TCL_FILE} "close_project\n")

    add_custom_command (OUTPUT ${OUTPUT_FILE_XCI} ${OUTPUT_FILE_VERILOG}
                        COMMAND ${VIVADO_NATIVE} -nojournal -mode batch -log ${TARGET_NAME}.log -source ${TCL_FILE} -notrace
                        COMMENT "Copying IP Core ${IP_NAME} from Block Design to ${TARGET_NAME}"
			DEPENDS ${EXPORTED_TCL})

    add_custom_target (${TARGET_NAME} ALL
                       COMMENT "Checking IP Core ${TARGET_NAME} (from Block Design)"
                       DEPENDS ${OUTPUT_FILE_XCI} ${OUTPUT_FILE_VERILOG} ${BLOCK_IN})

    set_property (TARGET ${TARGET_NAME}
                         PROPERTY SOURCES ${OUTPUT_FILE_XCI})

    set_property (TARGET ${TARGET_NAME}
                         PROPERTY OUTPUT_NAME ${OUTPUT_FILE_VERILOG})

  else ()

    message (SEND_ERROR "vivado_block_ip: required parameter missing")

  endif()

endfunction (vivado_block_ip)

# Function: vivado_ip_gen
# Parameters:
#   - TARGET_NAME:        target name
#   - IP_NAME:            IP name (in catalog)
#   - PROPERTIES:         list of properties for IP core (optional)
#   - IPCORE_DIR          directory for output file (xci)
#
# This functions sets two properties on the TARGET:
#   SOURCES      ${TARGET_NAME}.xci
#   OUTPUT_NAME  ${TARGET_NAME}_stub.v

function (vivado_ip_gen)

  # set all keywords and their values to ""
  set (FUNCTION_KEYWORDS
       TARGET_NAME
       IP_NAME
       PROPERTIES
       IPCORE_DIR)

  # reset local variables
  foreach(keyword ${FUNCTION_KEYWORDS})
    set (${keyword} "")
  endforeach(keyword)

  # parse input
  foreach (arg ${ARGV})
    list (FIND FUNCTION_KEYWORDS ${arg} ARGUMENT_IS_A_KEYWORD)
    if (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (CURRENT_PARAMETER ${arg})
      set (${CURRENT_PARAMETER} "")
    else (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (${CURRENT_PARAMETER} ${${CURRENT_PARAMETER}} ${arg})
    endif (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
  endforeach (arg)

  if (TARGET_NAME AND IP_NAME AND IPCORE_DIR)

    file (TO_NATIVE_PATH ${XILINX_VIVADO} VIVADO_NATIVE)

    # Make sure IPCORE_DIR exists
    file (MAKE_DIRECTORY ${IPCORE_DIR})

    # Create TCL file
    set (TCL_FILE "${CMAKE_CURRENT_BINARY_DIR}/make-${TARGET_NAME}.tcl")
    file (WRITE  ${TCL_FILE} "create_project -part ${FPGAV3_PARTNUM} -in_memory\n")
    # Disable message 12-13650 (IP moved from original location) because it is not important
    file (APPEND ${TCL_FILE} "set_msg_config -id {Vivado 12-13650} -suppress\n")
    # Find the IP by searching repository based on IP_NAME
    file (APPEND ${TCL_FILE} "set ip_vlnv [get_ipdefs *:${IP_NAME}:* -filter {UPGRADE_VERSIONS == \"\"}]\n")
    # Display the version found (not required -- for information only)
    file (APPEND ${TCL_FILE} "set ip_version [lindex [split \${ip_vlnv} \":\"] 3]\n")
    file (APPEND ${TCL_FILE} "puts \"Found ${IP_NAME}, version \${ip_version}\"\n")
    # Create the IP in the specified directory (IPCORE_DIR). Note that IP will be created
    # in a subdirectory named TARGET_NAME.
    file (APPEND ${TCL_FILE} "create_ip -vlnv \${ip_vlnv} -module_name ${TARGET_NAME} -dir ${IPCORE_DIR} -force\n")
    # Set properties for IP core
    file (APPEND ${TCL_FILE} "set_property -dict [list \\\n")
    foreach (prop ${PROPERTIES})
      file (APPEND ${TCL_FILE} "    ${prop} \\\n")
    endforeach (prop)
    file (APPEND ${TCL_FILE} "    ] [get_ips ${TARGET_NAME}]\n")
    # Generate targets and synthesize IP core
    file (APPEND ${TCL_FILE} "generate_target -force {instantiation_template synthesis} [get_ips ${TARGET_NAME}]\n")
    file (APPEND ${TCL_FILE} "puts \"Synthesize IP ${TARGET_NAME}\"\n")
    # For some reason, Vivado complains that it cannot overwrite dcp file
    file (APPEND ${TCL_FILE} "file delete -force \"${IPCORE_DIR}/${TARGET_NAME}/${TARGET_NAME}.dcp\"\n")
    file (APPEND ${TCL_FILE} "synth_ip -force [get_ips ${TARGET_NAME}]\n")
    file (APPEND ${TCL_FILE} "close_project\n")

    set (OUTPUT_DIR  "${IPCORE_DIR}/${TARGET_NAME}")
    set (OUTPUT_FILE_XCI     "${OUTPUT_DIR}/${TARGET_NAME}.xci")
    set (OUTPUT_FILE_VERILOG "${OUTPUT_DIR}/${TARGET_NAME}_stub.v")

    add_custom_command (OUTPUT ${OUTPUT_FILE_XCI} ${OUTPUT_FILE_VERILOG}
                        COMMAND ${VIVADO_NATIVE} -nojournal -mode batch -log ${TARGET_NAME}.log -source ${TCL_FILE} -notrace
                        COMMENT "Creating IP Core ${TARGET_NAME}")

    add_custom_target (${TARGET_NAME} ALL
                       COMMENT "Checking IP Core ${TARGET_NAME}"
                       DEPENDS ${OUTPUT_FILE_XCI} ${OUTPUT_FILE_VERILOG})

    set_property (TARGET ${TARGET_NAME}
                         PROPERTY SOURCES ${OUTPUT_FILE_XCI})

    set_property (TARGET ${TARGET_NAME}
                         PROPERTY OUTPUT_NAME ${OUTPUT_FILE_VERILOG})

  else ()

    message (SEND_ERROR "vivado_ip_gen: required parameter missing")

  endif()

endfunction (vivado_ip_gen)

# vivado_compile_fpga
#
#   - PROJ_NAME:       the project name (most output files will use this name)
#   - DEPENDENCIES:    dependencies for this target (e.g., IP cores)
#   - FPGA_PARTNUM:    the FPGA part number
#   - VERILOG_SOURCE:  list of Verilog source code (.v)
#   - XDC_FILE:        Primary user constraints file
#   - BOARD_XDC_FILE:  User constraints file for attached board (optional)
#   - IP_TARGETS:      List of IP targets (that produce XCI files)
#   - TOP_LEVEL:       Top level module name
#   - USER_MACROS:     Macro definitions (optional)
function (vivado_compile_fpga)

  # set all keywords and their values to ""
  set (FUNCTION_KEYWORDS
       PROJ_NAME
       DEPENDENCIES
       FPGA_PARTNUM
       VERILOG_SOURCE
       XDC_FILE
       BOARD_XDC_FILE
       IP_TARGETS
       INCLUDE_DIRS
       TOP_LEVEL
       USER_MACROS)

  # reset local variables
  foreach(keyword ${FUNCTION_KEYWORDS})
    set (${keyword} "")
  endforeach(keyword)

  # parse input
  foreach (arg ${ARGV})
    list (FIND FUNCTION_KEYWORDS ${arg} ARGUMENT_IS_A_KEYWORD)
    if (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (CURRENT_PARAMETER ${arg})
      set (${CURRENT_PARAMETER} "")
    else (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (${CURRENT_PARAMETER} ${${CURRENT_PARAMETER}} ${arg})
    endif (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
  endforeach (arg)

  if (PROJ_NAME AND FPGA_PARTNUM AND VERILOG_SOURCE AND XDC_FILE AND TOP_LEVEL)

    file (TO_NATIVE_PATH ${XILINX_VIVADO} VIVADO_NATIVE)

    set (OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/${PROJ_NAME}")
    file (MAKE_DIRECTORY ${OUTPUT_DIR})
    set (REPORT_DIR "${OUTPUT_DIR}/reports")
    file (MAKE_DIRECTORY ${REPORT_DIR})
    set (CHECKPOINT_DIR "${OUTPUT_DIR}/checkpoints")
    file (MAKE_DIRECTORY ${CHECKPOINT_DIR})

    # Create TCL file
    set (TCL_FILE "${CMAKE_CURRENT_BINARY_DIR}/make-${PROJ_NAME}.tcl")
    file (WRITE  ${TCL_FILE} "create_project -part ${FPGAV3_PARTNUM} -in_memory\n")

    # Disable message 12-13650 (IP moved from original location) because it is not important
    file (APPEND ${TCL_FILE} "set_msg_config -id {Vivado 12-13650} -suppress\n")
    foreach (vfile ${VERILOG_SOURCE})
      file (APPEND ${TCL_FILE} "read_verilog ${vfile}\n")
    endforeach (vfile)

    file (APPEND ${TCL_FILE} "read_xdc ${XDC_FILE}\n")
    if (BOARD_XDC_FILE)
      file (APPEND ${TCL_FILE} "read_xdc ${BOARD_XDC_FILE}\n")
    endif ()

    set (IP_SOURCE "")
    foreach (ip ${IP_TARGETS})
      get_property(xci_file TARGET ${ip} PROPERTY SOURCES)
      file (APPEND ${TCL_FILE} "read_ip ${xci_file}\n")
      get_property(verilog_file TARGET ${ip} PROPERTY OUTPUT_NAME)
      set (IP_SOURCE ${IP_SOURCE} ${verilog_file})
    endforeach (ip)

    # Synthesize
    file (APPEND ${TCL_FILE} "puts \"Starting synthesis of ${PROJ_NAME}\"\n")
    file (APPEND ${TCL_FILE} "synth_design -top ${TOP_LEVEL}")
    if (INCLUDE_DIRS)
      file (APPEND ${TCL_FILE} " -include_dirs \"")
      foreach (dir ${INCLUDE_DIRS})
        file (APPEND ${TCL_FILE} "${dir} ")
      endforeach (dir)
      file (APPEND ${TCL_FILE} "\"")
    endif ()
    foreach (def ${USER_MACROS})
      file (APPEND ${TCL_FILE} " -verilog_define ${def}")
    endforeach (def)
    file (APPEND ${TCL_FILE} "\n")
    file (APPEND ${TCL_FILE} "puts \"Finished synthesis, writing checkpoint (post_synth)\"\n")
    file (APPEND ${TCL_FILE} "write_checkpoint -force {${CHECKPOINT_DIR}/post_synth}\n")
    file (APPEND ${TCL_FILE} "report_timing_summary -file {${REPORT_DIR}/post_synth_timing_summary.rpt}\n")

    # Optimize and place
    file (APPEND ${TCL_FILE} "puts \"Starting to optimize and place ${PROJ_NAME}\"\n")
    # Suppress INFO message 32-702 (optimization did not improve timing on net)
    file (APPEND ${TCL_FILE} "set_msg_config -id {Physopt 32-702} -suppress\n")
    file (APPEND ${TCL_FILE} "opt_design\n")
    file (APPEND ${TCL_FILE} "place_design\n")
    file (APPEND ${TCL_FILE} "phys_opt_design\n")
    file (APPEND ${TCL_FILE} "puts \"Finished optimize and place, writing checkpoint (post_place)\"\n")
    file (APPEND ${TCL_FILE} "write_checkpoint -force {${CHECKPOINT_DIR}/post_place}\n")
    file (APPEND ${TCL_FILE} "report_timing_summary -file {${REPORT_DIR}/post_place_timing_summary.rpt}\n")

    # Route
    file (APPEND ${TCL_FILE} "puts \"Starting to route ${PROJ_NAME}\"\n")
    file (APPEND ${TCL_FILE} "route_design\n")
    file (APPEND ${TCL_FILE} "puts \"Finished route, writing checkpoint and reports (post_route)\"\n")
    file (APPEND ${TCL_FILE} "write_checkpoint -force {${CHECKPOINT_DIR}/post_route}\n")
    file (APPEND ${TCL_FILE} "report_timing_summary -file {${REPORT_DIR}/post_route_timing_summary.rpt}\n")
    file (APPEND ${TCL_FILE} "report_timing -sort_by group -max_paths 100 -path_type summary -file {${REPORT_DIR}/post_route_timing.rpt}\n")
    file (APPEND ${TCL_FILE} "report_drc -file {${REPORT_DIR}/post_route_drc.rpt}\n")
    file (APPEND ${TCL_FILE} "report_utilization -file {${REPORT_DIR}/post_route_util.rpt}\n")
    file (APPEND ${TCL_FILE} "report_clock_utilization -file {${REPORT_DIR}/clock_util.rpt}\n")
    file (APPEND ${TCL_FILE} "write_xdc -force {${REPORT_DIR}/${PROJ_NAME}_impl.xdc}\n")

    file (APPEND ${TCL_FILE} "puts \"Generating bitstream for ${PROJ_NAME}\"\n")
    file (APPEND ${TCL_FILE} "write_bitstream -force ${PROJ_NAME}.bit\n")
    file (APPEND ${TCL_FILE} "close_project\n")

    set (OUTPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/${PROJ_NAME}.bit")

    add_custom_command (OUTPUT ${OUTPUT_FILE}
      COMMAND ${VIVADO_NATIVE} -nojournal -mode batch -log "${OUTPUT_DIR}/${PROJ_NAME}.log" -source ${TCL_FILE} -notrace
      DEPENDS ${VERILOG_SOURCE} ${IP_SOURCE} ${XDC_FILE} ${BOARD_XDC_FILE})

    add_custom_target (${PROJ_NAME} ALL
                       DEPENDS ${OUTPUT_FILE} ${IP_TARGETS} ${DEPENDENCIES})

    set_property (TARGET ${PROJ_NAME}
                         PROPERTY OUTPUT_NAME ${OUTPUT_FILE})

  else ()

    message (SEND_ERROR "vivado_compile_fpga: required parameter missing")

  endif ()

endfunction (vivado_compile_fpga)
