# UseVivado
#
# This package assumes that find_package(Vivado) has been called,
# so that the XILINX_VIVADO program has been found.
#
# The basic approach is to use Vivado to create the block design, which is then
# exported (File..Export Block Design) as a TCL file, specified by the EXPORTED_TCL
# parameter. In that case, it is only necessary to put the TCL file under source
# code control, since the Vivado project is regenerated by running the TCL file.
#
# The vivado_block_build function creates a top-level TCL file, called
# make-${PROJ_NAME}.tcl, that calls ${EXPORTED_TCL}, creates the top-level Verilog
# wrapper, and generates the output files, including the final ${HW_FILE} used by Vitis.
#
# The easiest way to make changes to the block design is to open the project file
# ${PROJ_NAME}.xpr in the build directory, make the changes, and then export the
# TCL file again. This file can then be manually copied to the source directory
# to update ${EXPORTED_TCL} in the repository.
#
# Function: vivado_block_build
#
# Parameters:
#   - PROJ_NAME:         project name
#   - BD_NAME:           board name
#   - FPGA_PARTNUM:      FPGA part number
#   - EXPORTED_TCL       Input TCL file (exported from Vivado)
#   - HW_FILE            Output hardware file (XSA)
#

function (vivado_block_build ...)

  # set all keywords and their values to ""
  set (FUNCTION_KEYWORDS
       PROJ_NAME
       BD_NAME
       FPGA_PARTNUM
       EXPORTED_TCL
       HW_FILE)

  # reset local variables
  foreach(keyword ${FUNCTION_KEYWORDS})
    set (${keyword} "")
  endforeach(keyword)

  # parse input
  foreach (arg ${ARGV})
    list (FIND FUNCTION_KEYWORDS ${arg} ARGUMENT_IS_A_KEYWORD)
    if (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (CURRENT_PARAMETER ${arg})
      set (${CURRENT_PARAMETER} "")
    else (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (${CURRENT_PARAMETER} ${${CURRENT_PARAMETER}} ${arg})
    endif (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
  endforeach (arg)

  if (PROJ_NAME AND BD_NAME AND FPGA_PARTNUM AND EXPORTED_TCL AND HW_FILE)

    file(TO_NATIVE_PATH ${XILINX_VIVADO} VIVADO_NATIVE)

    get_filename_component (EXPORTED_TCL_NAME ${EXPORTED_TCL} NAME)
    set (EXPORTED_TCL_BIN "${CMAKE_CURRENT_BINARY_DIR}/${EXPORTED_TCL_NAME}")

    # Put the version check here, since the code below (FILE_UPDATE) is what needs
    # to be tested and possibly updated for different versions of Vivado.
    if (NOT (${Vivado_VERSION} STREQUAL "2022.2" OR
             ${Vivado_VERSION} STREQUAL "2023.1" OR
             ${Vivado_VERSION} STREQUAL "2023.2" OR
             ${Vivado_VERSION} STREQUAL "2024.1" OR
             ${Vivado_VERSION} STREQUAL "2024.2" ))
      message (WARNING "Vivado ${Vivado_VERSION} not yet tested")
    endif ()

    # For now, just replace version string in file, since the only substantive difference
    # between the TCL files exported by Vivado 2022.2, 2023.x, 2024.x are the version string
    # (other differences include reordering of some file content).
    # The current REGEX will match any version between "2020" and "2025", with a ".1" or ".2" suffix,
    # but this can be changed as needed. If file differences become more substantive, alternate solutions
    # include using CMake configure_file or having version-specific TCL files in the source tree.
    set (FILE_UPDATE "${CMAKE_CURRENT_BINARY_DIR}/make-update.cmake")
    file (WRITE  ${FILE_UPDATE} "# Automatically generated\n")
    file (APPEND ${FILE_UPDATE} "file (READ ${EXPORTED_TCL} FILE_CONTENTS)\n")
    file (APPEND ${FILE_UPDATE}
                 "string (REGEX REPLACE \"202[0-5].[1-2]\" ${Vivado_VERSION} FILE_CONTENTS \"\${FILE_CONTENTS}\")\n")
    file (APPEND ${FILE_UPDATE} "file (WRITE ${EXPORTED_TCL_BIN} \"\${FILE_CONTENTS}\")\n")

    add_custom_command (OUTPUT ${EXPORTED_TCL_BIN}
                       COMMAND ${CMAKE_COMMAND}
                       ARGS -P ${FILE_UPDATE}
                       COMMENT "Updating ${EXPORTED_TCL_NAME}"
                       DEPENDS ${EXPORTED_TCL})

    # Create TCL file
    set (TCL_FILE "${CMAKE_CURRENT_BINARY_DIR}/make-${PROJ_NAME}.tcl")
    file (WRITE  ${TCL_FILE} "create_project -force -part ${FPGA_PARTNUM} ${PROJ_NAME} ${CMAKE_CURRENT_BINARY_DIR}\n")
    file (APPEND ${TCL_FILE} "create_bd_design ${BD_NAME}\n")
    file (APPEND ${TCL_FILE} "source ${EXPORTED_TCL_BIN}\n")
    file (APPEND ${TCL_FILE} "make_wrapper -top -files [get_files ${BD_NAME}.bd]\n")
    file (APPEND ${TCL_FILE} "add_files ${CMAKE_CURRENT_BINARY_DIR}/${PROJ_NAME}.gen/sources_1/bd/${BD_NAME}/hdl/${BD_NAME}_wrapper.v\n")
    file (APPEND ${TCL_FILE} "generate_target all [get_files ${BD_NAME}.bd]\n")
    # Could add -minimal below
    file (APPEND ${TCL_FILE} "write_hw_platform -fixed -force -file ${HW_FILE}\n")
    file (APPEND ${TCL_FILE} "close_project\n")

    add_custom_command (OUTPUT ${HW_FILE}
                        COMMAND ${VIVADO_NATIVE} -nojournal -mode batch -source ${TCL_FILE}
                        DEPENDS ${EXPORTED_TCL_BIN})

    add_custom_target (${PROJ_NAME} ALL
                       DEPENDS ${HW_FILE})

    set_property (TARGET ${PROJ_NAME}
                         PROPERTY OUTPUT_NAME ${HW_FILE})
  else ()

    message (SEND_ERROR "vivado_block_build: required parameter missing")

  endif ()

endfunction (vivado_block_build)

# Function: vivado_block_ip
# Parameters:
#   - TARGET_NAME:       Target name
#   - IP_NAME:           IP name (in catalog)
#   - FPGA_PARTNUM:      FPGA part number
#   - EXPORTED_TCL       Input TCL file (exported from Vivado)
#   - IPCORE_DIR         Directory for output xci file (optional)

function (vivado_block_ip)

  # set all keywords and their values to ""
  set (FUNCTION_KEYWORDS
       TARGET_NAME
       IP_NAME
       FPGA_PARTNUM
       EXPORTED_TCL
       IPCORE_DIR)

  # reset local variables
  foreach(keyword ${FUNCTION_KEYWORDS})
    set (${keyword} "")
  endforeach(keyword)
  # Default IPCORE_DIR is current binary directory
  set (IPCORE_DIR ${CMAKE_CURRENT_BINARY_DIR})

  # parse input
  foreach (arg ${ARGV})
    list (FIND FUNCTION_KEYWORDS ${arg} ARGUMENT_IS_A_KEYWORD)
    if (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (CURRENT_PARAMETER ${arg})
      set (${CURRENT_PARAMETER} "")
    else (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (${CURRENT_PARAMETER} ${${CURRENT_PARAMETER}} ${arg})
    endif (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
  endforeach (arg)

  if (TARGET_NAME AND IP_NAME AND FPGA_PARTNUM AND EXPORTED_TCL)

    file(TO_NATIVE_PATH ${XILINX_VIVADO} VIVADO_NATIVE)

    # Following copied from vivado_block_build. This is allowed if the output files
    # are created in different directories (otherwise, would have to rename).
    # Probably would be better to have a separate target that is run once.
    get_filename_component (EXPORTED_TCL_NAME ${EXPORTED_TCL} NAME)
    set (EXPORTED_TCL_BIN "${CMAKE_CURRENT_BINARY_DIR}/${EXPORTED_TCL_NAME}")

    set (FILE_UPDATE "${CMAKE_CURRENT_BINARY_DIR}/make-update-ip.cmake")
    file (WRITE  ${FILE_UPDATE} "# Automatically generated\n")
    file (APPEND ${FILE_UPDATE} "file (READ ${EXPORTED_TCL} FILE_CONTENTS)\n")
    file (APPEND ${FILE_UPDATE}
                 "string (REGEX REPLACE \"202[0-5].[1-2]\" ${Vivado_VERSION} FILE_CONTENTS \"\${FILE_CONTENTS}\")\n")
    file (APPEND ${FILE_UPDATE} "file (WRITE ${EXPORTED_TCL_BIN} \"\${FILE_CONTENTS}\")\n")

    add_custom_command (OUTPUT ${EXPORTED_TCL_BIN}
                       COMMAND ${CMAKE_COMMAND}
                       ARGS -P ${FILE_UPDATE}
                       COMMENT "Updating ${EXPORTED_TCL_NAME}"
                       DEPENDS ${EXPORTED_TCL})
    # End of code copied from vivado_block_build

    set (OUTPUT_DIR  "${IPCORE_DIR}/${TARGET_NAME}")
    set (OUTPUT_FILE "${OUTPUT_DIR}/${TARGET_NAME}.xci")

    # CMake file to fix directories (gen_directory and OUTPUTDIR) in xci file
    set (FILE_UPDATE_XCI "${CMAKE_CURRENT_BINARY_DIR}/update-xci.cmake")
    file (WRITE  ${FILE_UPDATE_XCI} "# Automatically generated\n")
    file (APPEND ${FILE_UPDATE_XCI} "file (READ ${OUTPUT_FILE} FILE_CONTENTS)\n")
    file (APPEND ${FILE_UPDATE_XCI}
                 "string (REPLACE \"../.gen/sources_1/ip/${TARGET_NAME}\" \"${OUTPUT_DIR}\" FILE_CONTENTS \"\${FILE_CONTENTS}\")\n")
    file (APPEND ${FILE_UPDATE_XCI} "file (WRITE ${OUTPUT_FILE} \"\${FILE_CONTENTS}\")\n")

    # Create TCL file
    set (TCL_FILE "${CMAKE_CURRENT_BINARY_DIR}/make-${TARGET_NAME}.tcl")
    file (WRITE  ${TCL_FILE} "create_project -part ${FPGA_PARTNUM} -in_memory\n")
    file (APPEND ${TCL_FILE} "create_bd_design bd_temp\n")
    file (APPEND ${TCL_FILE} "source ${EXPORTED_TCL_BIN}\n")
    # Copy IP to IPCORE_DIR (after deleting any existing file)
    file (APPEND ${TCL_FILE} "file delete -force ${OUTPUT_DIR}\n")
    file (APPEND ${TCL_FILE} "copy_ip -name ${TARGET_NAME} -dir ${IPCORE_DIR} [get_ips *${IP_NAME}*]\n")
    file (APPEND ${TCL_FILE} "exec ${CMAKE_COMMAND} -P ${FILE_UPDATE_XCI}\n")
    file (APPEND ${TCL_FILE} "close_project\n")
    file (APPEND ${TCL_FILE} "create_project -part ${FPGA_PARTNUM} -in_memory\n")
    # Following does not seem to work (does not change where IP output is generated), so the update-xci.cmake
    # approach was used instead (see above).
    # file (APPEND ${TCL_FILE} "set_property CUSTOMIZED_DEFAULT_IP_LOCATION ${OUTPUT_DIR} [current_project]\n")
    file (APPEND ${TCL_FILE} "read_ip ${OUTPUT_FILE}\n")
    # Generate targets and synthesize IP core
    file (APPEND ${TCL_FILE} "set_property GENERATE_SYNTH_CHECKPOINT true [get_files ${TARGET_NAME}.xci]\n")
    file (APPEND ${TCL_FILE} "generate_target -force {instantiation_template synthesis} [get_ips ${TARGET_NAME}]\n")
    file (APPEND ${TCL_FILE} "synth_ip -force [get_ips ${TARGET_NAME}]\n")
    file (APPEND ${TCL_FILE} "close_project\n")

    add_custom_command (OUTPUT ${OUTPUT_FILE}
                        COMMAND ${VIVADO_NATIVE} -nojournal -mode batch -source ${TCL_FILE}
                        COMMENT "Copying IP Core ${IP_NAME} from Block Design to ${TARGET_NAME}"
			DEPENDS ${EXPORTED_TCL_BIN})

    add_custom_target (${TARGET_NAME} ALL
                       COMMENT "Checking IP Core ${TARGET_NAME} (from Block Design)"
                       DEPENDS ${OUTPUT_FILE})

    set_property (TARGET ${TARGET_NAME}
                         PROPERTY OUTPUT_NAME ${OUTPUT_FILE})

  else ()

    message (SEND_ERROR "vivado_block_ip: required parameter missing")

  endif()

endfunction (vivado_block_ip)

# Function: vivado_ip_gen
# Parameters:
#   - TARGET_NAME:        target name
#   - IP_NAME:            IP name (in catalog)
#   - PROPERTIES:         list of properties for IP core (optional)
#   - IPCORE_DIR          directory for output file (xci)

function (vivado_ip_gen)

  # set all keywords and their values to ""
  set (FUNCTION_KEYWORDS
       TARGET_NAME
       IP_NAME
       PROPERTIES
       IPCORE_DIR)

  # reset local variables
  foreach(keyword ${FUNCTION_KEYWORDS})
    set (${keyword} "")
  endforeach(keyword)

  # parse input
  foreach (arg ${ARGV})
    list (FIND FUNCTION_KEYWORDS ${arg} ARGUMENT_IS_A_KEYWORD)
    if (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (CURRENT_PARAMETER ${arg})
      set (${CURRENT_PARAMETER} "")
    else (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (${CURRENT_PARAMETER} ${${CURRENT_PARAMETER}} ${arg})
    endif (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
  endforeach (arg)

  if (TARGET_NAME AND IP_NAME AND IPCORE_DIR)

    file (TO_NATIVE_PATH ${XILINX_VIVADO} VIVADO_NATIVE)

    # Make sure IPCORE_DIR exists
    file (MAKE_DIRECTORY ${IPCORE_DIR})

    # Create TCL file
    set (TCL_FILE "${CMAKE_CURRENT_BINARY_DIR}/make-${TARGET_NAME}.tcl")
    file (WRITE  ${TCL_FILE} "create_project -part ${FPGAV3_PARTNUM} -in_memory\n")
    # Find the IP by searching repository based on IP_NAME
    file (APPEND ${TCL_FILE} "set ip_vlnv [get_ipdefs *${IP_NAME}*]\n")
    # Display the version found (not required -- for information only)
    file (APPEND ${TCL_FILE} "set ip_version [lindex [split \${ip_vlnv} \":\"] 3]\n")
    file (APPEND ${TCL_FILE} "puts \"Found ${IP_NAME}, version \${ip_version}\"\n")
    # Create the IP in the specified directory (IPCORE_DIR). Note that IP will be created
    # in a subdirectory named TARGET_NAM.
    file (APPEND ${TCL_FILE} "create_ip -vlnv \${ip_vlnv} -module_name ${TARGET_NAME} -dir ${IPCORE_DIR} -force\n")
    # Set properties for IP core
    foreach (prop ${PROPERTIES})
      file (APPEND ${TCL_FILE} "set_property ${prop} [get_ips ${TARGET_NAME}]\n")
    endforeach (prop)
    # Generate targets and synthesize IP core
    file (APPEND ${TCL_FILE} "generate_target -force {instantiation_template synthesis} [get_ips ${TARGET_NAME}]\n")
    file (APPEND ${TCL_FILE} "synth_ip -force [get_ips ${TARGET_NAME}]\n")
    file (APPEND ${TCL_FILE} "close_project\n")

    set (OUTPUT_FILE "${IPCORE_DIR}/${TARGET_NAME}/${TARGET_NAME}.xci")

    add_custom_command (OUTPUT ${OUTPUT_FILE}
                        COMMAND ${VIVADO_NATIVE} -nojournal -mode batch -source ${TCL_FILE}
                        COMMENT "Creating IP Core ${TARGET_NAME}")

    add_custom_target (${TARGET_NAME} ALL
                       COMMENT "Checking IP Core ${TARGET_NAME}"
                       DEPENDS ${OUTPUT_FILE})

    set_property (TARGET ${TARGET_NAME}
                         PROPERTY OUTPUT_NAME ${OUTPUT_FILE})

  else ()

    message (SEND_ERROR "vivado_ip_gen: required parameter missing")

  endif()

endfunction (vivado_ip_gen)

# vivado_compile_fpga
#
#   - PROJ_NAME:       the project name (most output files will use this name)
#   - DEPENDENCIES:    dependencies for this target (e.g., IP cores)
#   - FPGA_PARTNUM:    the FPGA part number
#   - VERILOG_SOURCE:  list of Verilog source code (.v)
#   - XDC_FILE:        User constraints file(s)
#   - IP_TARGETS:      List of IP targets (that produce XCI files)
#   - TOP_LEVEL:       Top level module name
#   - USER_MACROS:     Macro definitions (optional)
function (vivado_compile_fpga)

  # set all keywords and their values to ""
  set (FUNCTION_KEYWORDS
       PROJ_NAME
       DEPENDENCIES
       FPGA_PARTNUM
       VERILOG_SOURCE
       XDC_FILE
       IP_TARGETS
       INCLUDE_DIRS
       TOP_LEVEL
       USER_MACROS)

  # reset local variables
  foreach(keyword ${FUNCTION_KEYWORDS})
    set (${keyword} "")
  endforeach(keyword)

  # parse input
  foreach (arg ${ARGV})
    list (FIND FUNCTION_KEYWORDS ${arg} ARGUMENT_IS_A_KEYWORD)
    if (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (CURRENT_PARAMETER ${arg})
      set (${CURRENT_PARAMETER} "")
    else (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (${CURRENT_PARAMETER} ${${CURRENT_PARAMETER}} ${arg})
    endif (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
  endforeach (arg)

  #if (PROJ_NAME AND FPGA_PARTNUM AND VERILOG_SOURCE AND XDC_FILE AND TOP_LEVEL)
  if (PROJ_NAME AND FPGA_PARTNUM AND VERILOG_SOURCE AND TOP_LEVEL)

    file(TO_NATIVE_PATH ${XILINX_VIVADO} VIVADO_NATIVE)

    set (OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/${PROJ_NAME}")
    file (MAKE_DIRECTORY ${OUTPUT_DIR})

    # Create TCL file
    set (TCL_FILE "${CMAKE_CURRENT_BINARY_DIR}/make-${PROJ_NAME}.tcl")
    file (WRITE  ${TCL_FILE} "create_project -part ${FPGAV3_PARTNUM} -in_memory\n")

    foreach (vfile ${VERILOG_SOURCE})
      file (APPEND ${TCL_FILE} "read_verilog ${vfile}\n")
    endforeach (vfile)

    foreach (xfile ${XDC_FILE})
      file (APPEND ${TCL_FILE} "read_xdc ${xfile}\n")
    endforeach (xfile)

    foreach (ip ${IP_TARGETS})
      get_property(xci_file TARGET ${ip} PROPERTY OUTPUT_NAME)
      file (APPEND ${TCL_FILE} "read_ip ${xci_file}\n")
    endforeach (ip)

    file (APPEND ${TCL_FILE} "synth_design -top ${TOP_LEVEL}")
    if (INCLUDE_DIRS)
      file (APPEND ${TCL_FILE} " -include_dirs \"")
      foreach (dir ${INCLUDE_DIRS})
        file (APPEND ${TCL_FILE} "${dir} ")
      endforeach (dir)
      file (APPEND ${TCL_FILE} "\"")
    endif ()
    foreach (def ${USER_MACROS})
      file (APPEND ${TCL_FILE} " -verilog_define ${def}")
    endforeach (def)
    file (APPEND ${TCL_FILE} "\n")

    set (OUTPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/${PROJ_NAME}.bit")

    add_custom_command (OUTPUT ${OUTPUT_FILE}
      COMMAND ${VIVADO_NATIVE} -nojournal -mode batch -source ${TCL_FILE}
      DEPENDS ${VERILOG_SOURCE} ${XDC_FILE})

    add_custom_target (${PROJ_NAME} ALL
                       DEPENDS ${OUTPUT_FILE} ${IP_TARGETS} ${DEPENDENCIES})

    set_property (TARGET ${PROJ_NAME}
                         PROPERTY OUTPUT_NAME ${OUTPUT_FILE})

  else ()

    message (SEND_ERROR "vivado_compile_fpga: required parameter missing")

  endif ()

endfunction (vivado_compile_fpga)
